name: Validate Flake
on: push
jobs:
  flakes-simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_version: 2.4
          nix_conf: experimental-features = nix-command flakes
      - run: nix flake check --show-trace
