---
name: Validate Flake & Packages
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches: [main]
  workflow_dispatch:  # allows manual triggering
  schedule:
    - cron: 0 0 * * 0  # runs weekly on Sunday at 00:00
jobs:
  validate-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake show
      - run: nix flake check
  
  get-packages:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - id: get-packages
        name: Get all packages from flake
        run: |
          # Get all packages from the flake and format as JSON array
          PACKAGES=$(nix flake show --json | jq -r '.packages."x86_64-linux" | keys | tostring')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
          echo "Found packages: $PACKAGES"
  
  build:
    needs: get-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.get-packages.outputs.packages) }}
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: andoriyu-flakes
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: cachix watch-exec andoriyu-flakes nix build .#${{matrix.pkg}}
