name: Validate Flake
on: push
jobs:
  validate-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_version: 2.4
          nix_conf: experimental-features = nix-command flakes
      - run: nix flake check --show-trace
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: ["git-cliff", "dart-sass"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_version: 2.4
          nix_conf: experimental-features = nix-command flakes
      - run: nix build .#${{matrix.pkg}} || ls -lsa /nix/store/lky0g3fzm3i9923yxjpig4cv2p8hxbsf-dart-sass-1.49.0-linux-x64.tar.gz
