---
name: Validate Flake & Packages
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
  workflow_dispatch:  # allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # runs weekly on Sunday at 00:00

jobs:
  validate-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake show
      - run: nix flake check
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: ["git-cliff", "dart-sass", "atlas", "cargo-expand-nightly"]
        platform: ["x86_64-linux", "aarch64-linux"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = aarch64-linux arm-linux
      - name: aarch64-linux-emulation
        if: matrix.platform == 'aarch64-linux'
        run: |
         DEBIAN_FRONTEND=noninteractive
         sudo apt-get update -q -y && sudo apt-get install -q -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
         sudo update-binfmts --display
      - uses: cachix/cachix-action@v10
        with:
          name: andoriyu-flakes
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: cachix watch-exec andoriyu-flakes nix build .#packages.${{matrix.platform}}.${{matrix.pkg}}
